{% set version = "0.9.10" %}
{% set sha256 = "eb8fb2c3e4b6e2d336608377050892b54c3c983b646c561836550863003c05d7" %}

package:
  name: libunistring
  version: {{ version }}

source:
  fn: libunistring-{{ version }}.tar.xz
  url: http://ftpmirror.gnu.org/libunistring/libunistring-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    # 5/25/2021 (PJY): Got a failure during 'make check' for 'test-thread_create'.
    # Found this issue thread: https://bugs.launchpad.net/ubuntu/+source/libunistring/+bug/1813587/comments/10
    # which points to this upstream patch: https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commitdiff;h=cca32830b57e91f837c01d15b8732f23ff97fc36
    # This is the upstream patch.
    - 0001_force_linking_with_-lpthread.patch  # [linux and aarch64]

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libunistring
    - {{ pin_subpackage('libunistring', min_pin='x', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -e $PREFIX/lib/libunistring${SHLIB_EXT}

about:
  home: https://www.gnu.org/software/libunistring
  license: LGPL
  summary: This library provides functions for manipulating Unicode strings and for manipulating C strings according to the Unicode standard.

extra:
  recipe-maintainers:
    - stefan-balke
    - bgruening
    - chenghlee
