{% set version = "0.9.10" %}

package:
  name: libunistring
  version: {{ version }}

source:
  fn: libunistring-{{ version }}.tar.xz
  url: http://ftpmirror.gnu.org/libunistring/libunistring-{{ version }}.tar.xz
  sha256: a82e5b333339a88ea4608e4635479a1cfb2e01aafb925e1290b65710d43f610b

build:
  number: 1000
  skip: True  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libunistring
    - {{ pin_subpackage('libunistring', min_pin='x', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:

test:
  commands:
    - test -e $PREFIX/lib/libunistring.so  # [linux]
    - test -e $PREFIX/lib/libunistring.a  # [osx]
    - test -e $PREFIX/lib/libunistring.dylib  # [osx]

about:
  home: https://www.gnu.org/software/libunistring
  license: LGPL
  summary: This library provides functions for manipulating Unicode strings and for manipulating C strings according to the Unicode standard.

extra:
  recipe-maintainers:
    - stefan-balke
    - bgruening
