{% set version = "1.0" %}
{% set sha256 = "5bab55b49f75d77ed26b257997e919b693f29fd4a1bc22e0e6e024c246c72741" %}

package:
  name: libunistring
  version: {{ version }}

source:
  fn: libunistring-{{ version }}.tar.xz
  url: http://ftpmirror.gnu.org/libunistring/libunistring-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libunistring
    - {{ pin_subpackage('libunistring', min_pin='x', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - libtool
  host:

test:
  commands:
    - test -e $PREFIX/lib/libunistring${SHLIB_EXT}

about:
  home: https://www.gnu.org/software/libunistring
  license: LGPL
  summary: This library provides functions for manipulating Unicode strings and for manipulating C strings according to the Unicode standard.

extra:
  recipe-maintainers:
    - stefan-balke
    - bgruening
    - chenghlee
