travis:
  secure:
    BINSTAR_TOKEN: Q232s/kik6snwlUL5BjBWkHnFtJwnA93neTrva/aZf7Fdz/ufTMRq7V0WnT84x42OlWPJ8STUWYE61NTctBYJ05KP/pG1PAFedGjvCVzaYDacPOgprtspgmaP9+++xh2dPXW8lgd/prMFQAklPN9RLg3NZ4gmh8mpAjtn8Hdhtp/32E62+THEu4RBAmtM4ETBBAR2MPodfo10N3Z94deRN55h+Qtq/OZiMBVlaQmWv1S8RUbcbXqMd5ll8eP98PwRc7O2T8BgDMSaP3GHOtthp+1GbgFTMmA6tpubPLJawcc9EWjrCPpuJg0bGIvJ5oY+6nSo5R8k4TxGq3/1VkzNa3JrN2/KKB6R872Or3XSiL+kV9j5f1JAJg5leWppx+ng1Wp6+cUFBwWLstS8kGw9XLf3LNOGSyqutkZPdfAkC3gFzjHk4TQpx5bPD812BQkz4efyYzcm+8roAJb4pDJ8dmoe8EiHlHEeXOhHDSdxyuBMIJ26CeBFAqkcgpnn5m43xf4ix2kQS5u9nfG+JpK1WFkPLhxzlE/TEKz/T3sa5yyaeaoFkJ4eoorezrGuI3IrKPldwJX2RUp5N6nQkSfd304N+GU6lTVAA8Nhl4mwmJmWz/rGBUTonR66RXwKdgl3ZoZg9v8fDiOgSlV9JGH9FGxquDU1KrlL/0LpcykCt8=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
