appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GTzZKHZrtFnLRdGOCs5/0fGGLzZ267VI1NPVpH3IBHJPv8odHmee/sJFjjxzjay342v88XAiO1VH4tYxz/TBGLmqUL5/U8wP625SX3MZl4WY5yL9+i3p+JB8PU1KPIVC7AlatxHjhaXe9JVcKWiRvsqhtIRvSWDmbJryI9LRACATskTabZyZqbncgLwE6ud04fv2DNQoqV379Ifb1Hdr7cr9Di1QlbGpFkapRJ42Mah+sbj64YJdvkp2bgFRbJIPjS/owXcIpoMGg1jzFgOamJPBpxfeo6wu+OB0bxpjyN188One04jen94VXDaMXXO1yA3LqpmZ6/VQ0C4aUNdzxN2OHRf2Wh9pMPrpiaLXDxMDpkSrmu50KD4OrDGibCWuE6V3vxY6eiuo+aj7/Ds61v2egaU0WUMPf3Q1tJZ5mK89RrqpN7KQN+QwIjFcZrH41vdMmh5FCzK1UtqssStN98bhjszHiu8Kq2FNDYZuR5lq5lpZBPg6xKLSW9UmInMPXdh3F1D+zvzHe8UixIjKtQuu/DNroVohVcyjCPk577sWLwYqTUpP5hC4PVLzkqlx8qF4GO8svWnaqZm8ni5KjrO5EzZfL7ebnMNlfRYjUqVNUFLJ1AXJnb2XmMVaa+6O1tk856q7Y6MWZCGZbkPZVLq29sHT+BRGytOaGcrwOU4=}
