travis:
  secure:
    BINSTAR_TOKEN: e/geelIYpE/J7BT6iJv4saayO/phxPkWETFe0RAMQviG+NceK/5go8DuVS+PhIvO1k7nnRVxKZjeU+B6rYNelD8El8j/KH9pDhiWBjHAcCI/+n6UaBVpMJEnQnblfYG+Suf3sMVg76tVOmtTwmv4nRATPYogN6f85+w5lBvwV/8hxnqpgBohrSV40Zic5KHVDc7mK5W5uz3YR7Xp0Fla2VL84Y2pGDmWN1mViuT6CfmUfuCvAzBfpCPzVJNX2lU5fdd/KDXlF5BQoIYSiFFxhLiSKkBwS3/Jgvrmb/u7fBgnjYamhcqwH2zxlGb1taAapQIRA6TkU18aVp6/SK8al+dXxuWUGDrADpyxMoAPfFg7E8QFGiqhZ3I3X+puQw6LrbBIHHwEIsOZuYYH8QNTgSwkcchO3NzTXhW36W+W3wnosgNYpTW5sKLpIbex0b3jG2KnmhawGto0UdDi3aGdqQVqczGRtzTgIWAQg0+VdDBevrhrTuLhQg+L951VQZXuiW3PZjxekwRCBhvKYzIQFC3KyCB0G9AJLlhCiNaBhyyZTm2vejx8QrLhf/873+4AdZ8QiRDRvCugXSEZaf9v6G8le20wBNlPy6eyThoohE9TGYTrYrSu34rljxxBbWNLEfy/hjPPAm1epyHox2hZjL9NZajqWSZZfw4wECNXjgI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
